import { Beer } from "./[id]";

export const database: Record<string, Beer> = {
  "ipa-solar": {
    "name": "IPA Solar",
    "ibu": 50,
    "description": "IPA Solar  uma cerveja premiada que encanta os amantes do lopulo. Com um aroma ctrico intenso e um sabor marcante, esta IPA oferece uma exploso de frescor a cada gole. O amargor equilibrado  complementado por um corpo leve e refrescante, tornando-a perfeita para qualquer ocasio.",
    "type": "IPA",
    "volume": 500,
    "brewery": "Brewmasters do Sol",
    "color": "Dourada",
    "glass": "Pint",
    "body": 60,
    "aroma": 75,
    "malt": 65,
    "harmonization": [
      "Grilled Shrimp",
      "Thai Curry",
      "Blue Cheese",
      "Mango Salsa",
      "Lemon Tart"
    ],
    "minimum_temperature": 4,
    "maximum_temperature": 7,
    "alcohol_content": 6
  },
  "paradise-pilsner": {
    "name": "Paradise Pilsner",
    "ibu": 15,
    "description": "Paradise Pilsner  uma cerveja refrescante que combina a leveza do estilo Pilsen com notas ctricas. Seu sabor suave e corpo leve so complementados por um aroma fresco, tornando-a perfeita para os dias quentes. Uma verdadeira celebrao dos tr3picos em cada gole.",
    "type": "Pilsen",
    "volume": 500,
    "brewery": "Espuma dos Deuses",
    "color": "Dourada",
    "glass": "Copo Pilsen",
    "body": 35,
    "aroma": 60,
    "malt": 40,
    "harmonization": [
      "Grilled Chicken",
      "Bratwurst",
      "Swiss Cheese",
      "Apple Strudel",
      "Crab Cakes"
    ],
    "minimum_temperature": 4,
    "maximum_temperature": 7,
    "alcohol_content": 5
  },
  "cactus-shadow-stout": {
    "name": "Cactus Shadow Stout",
    "ibu": 45,
    "description": "Cactus Shadow Stout  uma cerveja robusta e intensa, com sabores profundos de malte torrado e notas de caf. Seu corpo encorpado e cremoso proporciona uma experiancia rica e satisfat3ria. Uma homenagem   cultura sertaneja, refletida em cada detalhe desta cerveja.",
    "type": "Stout",
    "volume": 500,
    "brewery": "Espuma dos Deuses",
    "color": "Preta",
    "glass": "Pint",
    "body": 85,
    "aroma": 75,
    "malt": 85,
    "harmonization": [
      "Chocolate Brownies",
      "Beef Wellington",
      "Aged Cheddar",
      "Black Coffee",
      "Pecan Pie"
    ],
    "minimum_temperature": 5,
    "maximum_temperature": 9,
    "alcohol_content": 7
  },
  "citrus-surf-ipa": {
    "name": "Citrus Surf IPA",
    "ibu": 50,
    "description": "Citrus Surf IPA  uma cerveja refrescante com uma exploso de sabores tropicais. Com notas ctricas e frutadas, esta IPA oferece um amargor bem balanceado e um corpo mdio, tornando-a ideal para os dias ensolarados. Uma verdadeira celebrao dos sabores tropicais.",
    "type": "IPA",
    "volume": 500,
    "brewery": "Lopulo Feliz",
    "color": "Dourada",
    "glass": "Pint",
    "body": 70,
    "aroma": 80,
    "malt": 65,
    "harmonization": [
      "Fish Tacos",
      "Spicy Noodles",
      "Gorgonzola",
      "Pineapple Sorbet",
      "Crispy Tofu"
    ],
    "minimum_temperature": 5,
    "maximum_temperature": 8,
    "alcohol_content": 6
  },
  "stout-de-mandioca": {
    "name": "Stout de Mandioca",
    "ibu": 40,
    "description": "Stout de Mandioca  uma cerveja robusta com um toque brasileiro. Feita com mandioca, esta Stout oferece um sabor onico e marcante. As notas de malte torrado e chocolate so complementadas pelo corpo cremoso, proporcionando uma experiancia rica e autantica.",
    "type": "Stout",
    "volume": 500,
    "brewery": "Lopulo Feliz",
    "color": "Preta",
    "glass": "Pint",
    "body": 80,
    "aroma": 70,
    "malt": 90,
    "harmonization": [
      "BBQ Ribs",
      "Porterhouse Steak",
      "Parmesan Cheese",
      "Hot Chocolate",
      "Toasted Marshmallows"
    ],
    "minimum_temperature": 6,
    "maximum_temperature": 9,
    "alcohol_content": 7
  },
  "pilsen-cristal": {
    "name": "Pilsen Cristal",
    "ibu": 15,
    "description": "Pilsen Cristal  uma cerveja refrescante e leve, perfeita para qualquer ocasio. Com um corpo leve e um sabor suave, esta Pilsen oferece uma experiancia de bebida agradvel e revigorante. Ideal para momentos de descontrao.",
    "type": "Pilsen",
    "volume": 500,
    "brewery": "Cervejaria Rio Cristalino",
    "color": "Dourada",
    "glass": "Copo Pilsen",
    "body": 30,
    "aroma": 55,
    "malt": 35,
    "harmonization": [
      "Sushi",
      "Grilled Vegetables",
      "Brie Cheese",
      "Fruit Tart",
      "Seafood Pasta"
    ],
    "minimum_temperature": 4,
    "maximum_temperature": 7,
    "alcohol_content": 5
  },
  "tropical-breeze-lager": {
    "name": "Tropical Breeze Lager",
    "ibu": 15,
    "description": "Tropical Breeze Lager  uma cerveja refrescante com notas ctricas. Seu corpo leve e sabor suave so complementados por um aroma fresco, tornando-a ideal para os dias quentes. Uma celebrao dos sabores tropicais.",
    "type": "Pilsen",
    "volume": 500,
    "brewery": "Mestres da Cerveja",
    "color": "Dourada",
    "glass": "Copo Pilsen",
    "body": 35,
    "aroma": 60,
    "malt": 40,
    "harmonization": [
      "Grilled Pork",
      "Spicy Salsa",
      "Camembert Cheese",
      "Pineapple Upside-down Cake",
      "Fried Plantains"
    ],
    "minimum_temperature": 4,
    "maximum_temperature": 7,
    "alcohol_content": 5
  },
  "island-hopper-pils": {
    "name": "Island Hopper Pils",
    "ibu": 15,
    "description": "Island Hopper Pils  uma cerveja refrescante com um toque de ctricos. Seu corpo leve e sabor suave so complementados por um aroma fresco, tornando-a perfeita para os dias ensolarados. Uma celebrao dos tr3picos em cada gole.",
    "type": "Pilsen",
    "volume": 500,
    "brewery": "Barley Brothers",
    "color": "Dourada",
    "glass": "Copo Pilsen",
    "body": 35,
    "aroma": 60,
    "malt": 40,
    "harmonization": [
      "Crispy Fish",
      "Citrus Salad",
      "Havarti Cheese",
      "Mango Sorbet",
      "Garlic Bread"
    ],
    "minimum_temperature": 4,
    "maximum_temperature": 7,
    "alcohol_content": 5
  },
  "stout-do-sertao": {
    "name": "Stout do Sertao",
    "ibu": 45,
    "description": "Stout do Serto  uma cerveja robusta e intensa, com sabores profundos de malte torrado e notas de caf. Seu corpo encorpado e cremoso proporciona uma experiancia rica e satisfat3ria. Uma homenagem   cultura sertaneja, refletida em cada detalhe desta cerveja.",
    "type": "Stout",
    "volume": 500,
    "brewery": "Barley Brothers",
    "color": "Preta",
    "glass": "Pint",
    "body": 85,
    "aroma": 75,
    "malt": 85,
    "harmonization": [
      "Spicy Sausages",
      "Lamb Stew",
      "Aged Gouda",
      "Dark Chocolate",
      "Nutty Biscuits"
    ],
    "minimum_temperature": 6,
    "maximum_temperature": 9,
    "alcohol_content": 7
  },
  "pilsen-tropical": {
    "name": "Pilsen Tropical",
    "ibu": 15,
    "description": "Pilsen Tropical  uma cerveja refrescante com um toque de ctricos. Seu corpo leve e sabor suave so complementados por um aroma fresco, tornando-a ideal para os dias ensolarados. Uma celebrao dos tr3picos em cada gole.",
    "type": "Pilsen",
    "volume": 500,
    "brewery": "Cervejaria Lago Azul",
    "color": "Dourada",
    "glass": "Copo Pilsen",
    "body": 35,
    "aroma": 60,
    "malt": 40,
    "harmonization": [
      "Shrimp Skewers",
      "Tropical Salad",
      "Fresh Mozzarella",
      "Coconut Cake",
      "Chicken Wings"
    ],
    "minimum_temperature": 4,
    "maximum_temperature": 7,
    "alcohol_content": 5
  },
  "pernambuco-weiss": {
    "name": "Pernambuco Weiss",
    "ibu": 20,
    "description": "Pernambuco Weiss  uma cerveja de trigo refrescante com notas ctricas. Seu corpo leve e sabor frutado proporcionam uma experiancia agradvel e revigorante. Ideal para os dias quentes.",
    "type": "Weiss",
    "volume": 500,
    "brewery": "Trigo e Companhia",
    "color": "Dourada",
    "glass": "Copo Weiss",
    "body": 50,
    "aroma": 65,
    "malt": 55,
    "harmonization": [
      "Bratwurst",
      "German Potato Salad",
      "Muenster Cheese",
      "Apple Pie",
      "Soft Pretzels"
    ],
    "minimum_temperature": 5,
    "maximum_temperature": 8,
    "alcohol_content": 5
  },
  "ipa-tropical": {
    "name": "IPA Tropical",
    "ibu": 50,
    "description": "IPA Tropical  uma cerveja refrescante com uma exploso de sabores tropicais. Com notas ctricas e frutadas, esta IPA oferece um amargor bem balanceado e um corpo mdio, tornando-a ideal para os dias ensolarados. Uma verdadeira celebrao dos sabores tropicais.",
    "type": "IPA",
    "volume": 500,
    "brewery": "Trigo e Companhia",
    "color": "Dourada",
    "glass": "Pint",
    "body": 70,
    "aroma": 80,
    "malt": 65,
    "harmonization": [
      "Grilled Steak",
      "Bean Soup",
      "Aged Parmesan",
      "Vanilla Ice Cream",
      "Grilled Peaches"
    ],
    "minimum_temperature": 4,
    "maximum_temperature": 7,
    "alcohol_content": 6
  }
};